// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.refscout.app' | 'https://api.staging.refscout.app' | (string & {});
};

export const ModuleId = {
    BIBCHECK: 'bibcheck',
    GLOSSARY: 'glossary',
    PRESUBMIT: 'presubmit',
    CITE: 'cite'
} as const;

export type ModuleId = typeof ModuleId[keyof typeof ModuleId];

export const DocRole = {
    MANUSCRIPT: 'manuscript',
    BIBLIOGRAPHY: 'bibliography',
    GLOSSARY: 'glossary',
    VENUE_REQUIREMENTS: 'venue-requirements',
    UNKNOWN: 'unknown'
} as const;

export type DocRole = typeof DocRole[keyof typeof DocRole];

export const SourceFormat = {
    PDF: 'pdf',
    DOCX: 'docx',
    MD: 'md',
    TEX: 'tex',
    BIB: 'bib',
    GLS: 'gls',
    TXT: 'txt',
    TYPED: 'typed'
} as const;

export type SourceFormat = typeof SourceFormat[keyof typeof SourceFormat];

export const Severity = {
    CRITICAL: 'critical',
    WARNING: 'warning',
    INFO: 'info'
} as const;

export type Severity = typeof Severity[keyof typeof Severity];

export const JobState = {
    QUEUED: 'queued',
    RUNNING: 'running',
    PARTIAL: 'partial',
    FINISHED: 'finished',
    FAILED: 'failed',
    CANCELLED: 'cancelled'
} as const;

export type JobState = typeof JobState[keyof typeof JobState];

export const ModuleState = {
    QUEUED: 'queued',
    RUNNING: 'running',
    OK: 'ok',
    ERROR: 'error',
    SKIPPED: 'skipped'
} as const;

export type ModuleState = typeof ModuleState[keyof typeof ModuleState];

export const StageState = {
    PENDING: 'pending',
    RUNNING: 'running',
    DONE: 'done',
    ERROR: 'error',
    SKIPPED: 'skipped'
} as const;

export type StageState = typeof StageState[keyof typeof StageState];

export const LockReason = {
    REQUIRES_ACCOUNT: 'requires-account',
    REQUIRES_PAID: 'requires-paid',
    TRIAL_USED: 'trial-used',
    PERIOD_ENDED: 'period-ended'
} as const;

export type LockReason = typeof LockReason[keyof typeof LockReason];

/**
 * A bibliographic database. The client names each one from its dictionary.
 */
export const SourceId = {
    CROSSREF: 'crossref',
    OPENALEX: 'openalex',
    SEMANTICSCHOLAR: 'semanticscholar',
    PUBMED: 'pubmed',
    ARXIV: 'arxiv',
    DOAJ: 'doaj',
    CORE: 'core',
    DATACITE: 'datacite',
    UNPAYWALL: 'unpaywall',
    EUROPEPMC: 'europepmc'
} as const;

/**
 * A bibliographic database. The client names each one from its dictionary.
 */
export type SourceId = typeof SourceId[keyof typeof SourceId];

/**
 * Offsets are Unicode code points, which is the unit Python counts in natively and the
 * unit every measurement of text in this contract uses (section 5.3).
 *
 */
export type OffsetUnit = 'codepoints';

/**
 * Substitutions the client places into the wording it holds for a key.
 */
export type Params = {
    [key: string]: string | number;
};

/**
 * A key into the client's dictionary, such as `bibcheck.retracted_entry`.
 */
export type DictionaryKey = string;

export type Sha256Hex = string;

/**
 * An offset in Unicode code points.
 */
export type CpOffset = number;

export type Counts = {
    critical: number;
    warning: number;
    info: number;
};

export type ApiError = {
    error: {
        /**
         * An enumerated code from section 11.
         */
        code: string;
        requestId: string;
        params?: Params;
        /**
         * The JSON path of the field that failed validation.
         */
        field?: string;
        retryAfterSec?: number;
        /**
         * English, for logs and developers.
         */
        message?: string;
    };
};

/**
 * The document information the parser read out of the file, which PreSubmit reads for
 * anonymity. The six standard keys are named; XMP entries and custom document properties
 * travel alongside them and are where a name most often survives (section 4.1.3).
 *
 */
export type DocMeta = {
    Author?: string;
    Title?: string;
    Subject?: string;
    Creator?: string;
    Producer?: string;
    Keywords?: string;
    [key: string]: string | undefined;
};

/**
 * The venue this document targets. `preset` carries the preset id in `source`; `url` and
 * `text` carry the requirements in `text`; `file` names the requirements document in this
 * same job through `docId` (section 4.1.2).
 *
 */
export type VenueRef = unknown & {
    kind: 'preset' | 'url' | 'text' | 'file';
    /**
     * What the user entered - a preset id, an address, or a file name.
     */
    source: string;
    /**
     * The requirements as text.
     */
    text?: string;
    /**
     * The document in this job carrying `role: venue-requirements` and `checks: []`.
     *
     */
    docId?: string;
};

export type SubmitDocument = {
    /**
     * Minted by the client and preserved verbatim in every response.
     */
    docId: string;
    /**
     * The raw file-system name, so that a document named in a support conversation can be
     * found again. Carried as data.
     *
     */
    name: string;
    role: DocRole;
    format: SourceFormat;
    /**
     * What to do with this document. Empty for a document brought as an input to another
     * document's checks.
     *
     */
    checks: Array<ModuleId>;
    /**
     * docIds of other documents in this job that the checks on this document read - a
     * manuscript names its bibliography here (section 4.1.1).
     *
     */
    uses?: Array<string>;
    /**
     * The content, verbatim.
     */
    text: string;
    /**
     * SHA-256 of the UTF-8 bytes of `text`, recomputed by the server.
     */
    textSha256: Sha256Hex;
    /**
     * The length of `text` in Unicode code points, recomputed by the server.
     */
    cpLength: CpOffset;
    meta?: DocMeta;
    venue?: VenueRef;
};

/**
 * A settings snapshot for all four modules, sent in full so that a re-run inside the same
 * job is unambiguous.
 *
 */
export type CheckOptions = {
    bibcheck: {
        verifyLive: boolean;
        showOrphans: boolean;
        unifyKeys: boolean;
        /**
         * The shape of a citation key in the corrected bibliography, applied when
         * `unifyKeys` is true.
         *
         */
        keyFormat: 'author-year' | 'author-year-title' | 'author-title-year' | 'numeric';
        /**
         * The order of entries in the corrected bibliography. `cited-order` is the order
         * the manuscript cites them in; `original` keeps the order they arrived in.
         *
         */
        sortBy: 'author' | 'year' | 'title' | 'key' | 'cited-order' | 'original';
        countCommented: boolean;
    };
    glossary: {
        domain?: string;
    };
    presubmit: {
        checklist?: string;
        anonymity: boolean;
    };
    cite: {
        field?: string;
        maxPerClaim: number;
        instructions?: string;
    };
};

export type SubmitJobRequest = {
    documents: Array<SubmitDocument>;
    options: CheckOptions;
    /**
     * BCP-47. Sets the language of every word a module writes for a person to read:
     * `detail`, the content of an artifact, and any free text inside evidence. Codes and
     * dictionary keys are unaffected - the client composes those phrases itself
     * (section 4.1).
     *
     */
    locale: string;
};

export type SubmitJobResponse = {
    jobId: string;
    /**
     * Required for every read of this job (section 4.3).
     */
    jobToken: string;
    createdAt: string;
    entitlements: Entitlements;
};

export type RetryRequest = {
    /**
     * Which documents to re-run this module for. Omitted means every document where it is
     * in state `error`.
     *
     */
    docIds?: Array<string>;
};

export type Stage = {
    id: string;
    labelKey: DictionaryKey;
    labelParams?: Params;
    /**
     * Absent for job-wide stages.
     */
    docId?: string;
    state: StageState;
    startedAt?: string;
    /**
     * Present once the stage is done, so the row can show how long it took.
     */
    finishedAt?: string;
    progress?: {
        done: number;
        total: number;
    };
    detailKey?: DictionaryKey;
    detailParams?: Params;
};

export type ModuleStatus = {
    state: ModuleState;
    /**
     * 1 on the first run, raised by a retry (section 4.6).
     */
    attempt: number;
    /**
     * null for Cite and for a module that did not run.
     */
    score: number | null;
    /**
     * The numbers the interface shows for this card.
     */
    counts: Counts;
    headlineKey?: DictionaryKey;
    headlineParams?: Params;
    /**
     * Present exactly when state is `error` (section 11.4).
     */
    errorCode?: string;
    /**
     * Present exactly when state is `skipped`.
     */
    skippedReasonKey?: DictionaryKey;
    skippedReasonParams?: Params;
    /**
     * The address of the result body, appearing together with a terminal state. A path on
     * the API origin beginning with `/jobs/{jobId}/` (section 4.4).
     *
     */
    resultRef?: string;
    finishedAt?: string;
};

export type JobDocument = {
    docId: string;
    name: string;
    role: DocRole;
    /**
     * Recomputed by the server from the text it received.
     */
    textSha256: Sha256Hex;
    /**
     * Recomputed likewise.
     */
    cpLength: CpOffset;
    modules: {
        bibcheck?: ModuleStatus;
        glossary?: ModuleStatus;
        presubmit?: ModuleStatus;
        cite?: ModuleStatus;
    };
};

export type JobStatus = {
    id: string;
    createdAt: string;
    state: JobState;
    /**
     * Advisory: the client waits at least this long before the next poll, on top of its
     * own backoff.
     *
     */
    pollAfterMs?: number;
    stages: Array<Stage>;
    documents: Array<JobDocument>;
};

export type TextRef = {
    docId: string;
    textSha256: Sha256Hex;
    cpLength: CpOffset;
};

export type Artifact = {
    kind: 'bib' | 'tex' | 'md' | 'txt';
    labelKey: DictionaryKey;
    /**
     * The generated text; the client builds the file from it.
     */
    content: string;
};

export type ModuleResult = {
    module: ModuleId;
    /**
     * The document this result is about.
     */
    docId: string;
    attempt: number;
    offsetUnit: OffsetUnit;
    /**
     * Every document whose coordinates appear in this body: this result's own document
     * first, then each document named by an anchor's `docId`. Both values in each entry
     * are recomputed by the server from the text it received (section 4.4).
     *
     */
    texts: Array<TextRef>;
    issues: Array<Issue>;
    artifacts?: Array<Artifact>;
};

export type Issue = {
    /**
     * Stable across polls and across a module retry, unique within one document and
     * module, so that the user's marks stay attached to the right finding.
     *
     */
    issueId: string;
    code: string;
    severity: Severity;
    titleKey: DictionaryKey;
    params?: Params;
    /**
     * Plain text, which reaches the DOM as a text node.
     */
    detail?: string;
    anchors: Array<Anchor>;
    evidence?: Array<Evidence>;
    actions?: Array<IssueAction>;
    /**
     * The claims-and-candidates block Cite's card is built from (section 5.6).
     */
    cite?: CiteBlock;
};

/**
 * Tagged by `kind`. The last branch matches a kind this version of the schema does not
 * define, so an anchor of a new kind parses and the client shows the finding without a
 * jump target instead of losing the response (section 5.9).
 *
 */
export type Anchor = AnchorRange | AnchorQuote | AnchorPoint | AnchorBibkey | AnchorDocument | AnchorUnknown;

/**
 * An anchor whose kind this schema version does not define.
 */
export type AnchorUnknown = {
    kind: string;
    docId?: AnchorDocId;
};

/**
 * The document the place is in, when it is a different document from the one this result
 * is about. Every id used this way appears in `texts[]` (section 5.2).
 *
 */
export type AnchorDocId = string;

/**
 * Verbatim neighbouring text, present on every anchor of kind range, quote or point - 64
 * code points a side is ample. `prefix` ends exactly at the left boundary of the place and
 * `suffix` begins exactly at its right boundary. Optional here so that a missing context
 * costs its own anchor rather than the whole result; the rule that it is always sent is in
 * section 5.2.
 *
 */
export type AnchorContext = string;

/**
 * The module knows the exact coordinates. `quote` is verbatim equal to the submitted text
 * between the offsets, and its length in code points equals `to - from`. Context is
 * present, as on every anchor that has one (section 5.2).
 *
 */
export type AnchorRange = {
    kind: 'range';
    docId?: AnchorDocId;
    from: CpOffset;
    to: CpOffset;
    quote: string;
    prefix?: AnchorContext;
    suffix?: AnchorContext;
};

/**
 * The module knows the text of the place, which is the right answer for a module working
 * on its own representation of the document. Context is present, and here at least one of
 * `prefix`/`suffix` is non-empty, since there are no coordinates to fall back on.
 *
 */
export type AnchorQuote = {
    kind: 'quote';
    docId?: AnchorDocId;
    quote: string;
    prefix?: AnchorContext;
    suffix?: AnchorContext;
    /**
     * A hint about search order, used to rank candidates.
     */
    near?: CpOffset;
};

/**
 * An insertion position rather than a span. At least one of `prefix`/`suffix` is non-empty
 * and verbatim, which is what lets the point be verified and re-found after an edit.
 *
 */
export type AnchorPoint = {
    kind: 'point';
    docId?: AnchorDocId;
    at: CpOffset;
    prefix?: AnchorContext;
    suffix?: AnchorContext;
};

/**
 * A bibliography entry, addressed by a key that exists in the client's bibliography map or
 * literally in the submitted text.
 *
 */
export type AnchorBibkey = {
    kind: 'bibkey';
    docId?: AnchorDocId;
    bibkey: string;
};

/**
 * The finding is about the document as a whole.
 */
export type AnchorDocument = {
    kind: 'document';
    docId?: AnchorDocId;
};

/**
 * Tagged by `kind`. A fact of a kind this schema version does not define parses and the
 * card passes over it, showing the rest (section 5.9).
 *
 */
export type Evidence = EvidenceDoi | EvidenceUrl | EvidenceDate | EvidenceNumber | EvidenceText | EvidenceSource | EvidenceUnknown;

/**
 * A fact whose kind this schema version does not define.
 */
export type EvidenceUnknown = {
    kind: string;
};

/**
 * Rendered with rel="noopener noreferrer".
 */
export type HttpUrl = string;

export type EvidenceDoi = {
    kind: 'doi';
    value: string;
};

export type EvidenceUrl = {
    kind: 'url';
    value: HttpUrl;
};

export type EvidenceDate = {
    kind: 'date';
    labelKey: DictionaryKey;
    value: string;
};

export type EvidenceNumber = {
    kind: 'number';
    labelKey: DictionaryKey;
    value: number;
};

export type EvidenceText = {
    kind: 'text';
    labelKey: DictionaryKey;
    value: string;
};

export type EvidenceSource = {
    kind: 'source';
    labelKey: DictionaryKey;
    title: string;
    url?: HttpUrl;
};

/**
 * Tagged by `kind`. An action of a kind this schema version does not define parses and the
 * card does not offer that button, offering the rest (section 5.9).
 *
 */
export type IssueAction = ActionCopy | ActionReplace | ActionOpenSource | ActionDownload | ActionUnknown;

/**
 * An action whose kind this schema version does not define.
 */
export type ActionUnknown = {
    kind: string;
};

export type ActionCopy = {
    kind: 'copy';
    labelKey?: DictionaryKey;
    value: string;
};

/**
 * The ready replacement text the Apply button inserts. `anchorIndex` names the anchor it
 * applies to, and that anchor is of kind `range`.
 *
 */
export type ActionReplace = {
    kind: 'replace';
    labelKey?: DictionaryKey;
    value: string;
    anchorIndex?: number;
};

export type ActionOpenSource = {
    kind: 'openSource';
    labelKey?: DictionaryKey;
    url: HttpUrl;
};

export type ActionDownload = {
    kind: 'download';
    labelKey?: DictionaryKey;
    /**
     * An index into `artifacts[]` of this module result.
     */
    artifact: number;
};

/**
 * A work as the databases returned it. Every field is third-party data and reaches the DOM
 * as a text node.
 *
 */
export type BiblioRecord = {
    title: string;
    authors: Array<string>;
    year?: number;
    venue?: string;
    citedBy?: number;
    doi?: string;
    url?: HttpUrl;
    openAccess: boolean;
    sources: Array<SourceId>;
    abstract?: string;
};

export type CiteCandidate = BiblioRecord & {
    /**
     * Stable within this result; the client marks acceptance by it.
     */
    candidateId: string;
    relevance: number;
    /**
     * The work is already in this document's bibliography.
     */
    alreadyCited: boolean;
    /**
     * Shown under the "Potentially low relevance" heading.
     */
    lowRelevance: boolean;
};

export type CiteBlock = {
    /**
     * The search query the module used, shown on the card.
     */
    query: string;
    candidates: Array<CiteCandidate>;
};

export type ModuleEntitlement = {
    allowed: boolean;
    lockReason?: LockReason;
};

/**
 * Two independent answers. `modules[m].allowed` is the only source for the lock on module
 * m; `access` is the only source for what the launch row says about the period. Neither is
 * derived from the other: a trial run carries `allowed: true` with `access: false`
 * (section 6.1).
 *
 */
export type Entitlements = {
    role: 'anonymous' | 'free' | 'paid';
    /**
     * Whether paid access is open right now.
     */
    access: boolean;
    /**
     * The end of the current period, when the server names one.
     */
    periodEndsAt?: string;
    modules: {
        bibcheck: ModuleEntitlement;
        glossary: ModuleEntitlement;
        presubmit: ModuleEntitlement;
        cite: ModuleEntitlement;
    };
};

export type ScoutRequest = {
    query: string;
    limit: 10 | 25 | 50 | 100;
    locale?: string;
};

export type ScoutResult = BiblioRecord & {
    /**
     * Stable within this response; the feedback call names it.
     */
    resultId: string;
    relevance?: number;
};

export type ScoutResponse = {
    results: Array<ScoutResult>;
    /**
     * Which databases answered.
     */
    searchedSources: Array<SourceId>;
    /**
     * Which databases timed out or failed, so that the interface can say a partial answer
     * is partial.
     *
     */
    degraded?: Array<SourceId>;
};

export type ScoutFeedbackRequest = {
    resultId: string;
    vote: 'up' | 'down';
};

export type Venue = {
    id: string;
    name: string;
    publisher?: string;
};

export type VenuesResponse = {
    venues: Array<Venue>;
};

export type VenueFetchRequest = {
    url: HttpUrl;
};

export type VenueFetchResponse = {
    state: 'ready' | 'not-requirements';
    /**
     * The extracted requirements as plain text; present when state is `ready`.
     */
    text?: string;
    title?: string;
    fetchedAt: string;
};

export type Breadcrumb = {
    action: string;
    outcome: string;
    ts: string;
};

/**
 * Present on an event of kind `user_report`. The client shows the complete contents of the
 * report before it is sent (section 9.1.1).
 *
 */
export type UserReport = {
    /**
     * What the person wrote.
     */
    message: string;
    /**
     * A fragment of the document the person selected in the editor and confirmed
     * attaching.
     *
     */
    excerpt?: string;
};

export type ClientEvent = {
    id: string;
    ts: string;
    kind: 'js_error' | 'promise_rejection' | 'react_error' | 'worker_error' | 'api_error' | 'schema_error' | 'network_error' | 'extract_failed' | 'extract_suspicious' | 'slow_operation' | 'stalled_action' | 'blocked_action' | 'repeated_click' | 'anchor_degraded' | 'anchor_rejected' | 'anchor_budget' | 'storage_pressure' | 'user_report';
    /**
     * An enumeration, optionally with a path, such as
     * `SCHEMA_MISMATCH:job.documents[0].modules.bibcheck.score`.
     *
     */
    code: string;
    /**
     * Identical events are collapsed by it with a count.
     */
    fingerprint: string;
    count: number;
    release: string;
    route: string;
    locale: string;
    theme: 'light' | 'dark';
    viewport: {
        w: number;
        h: number;
    };
    /**
     * Numbers, flags and enumerated strings.
     */
    context: {
        [key: string]: number | boolean | string;
    };
    breadcrumbs: Array<Breadcrumb>;
    /**
     * Ties the event to a server log line.
     */
    requestId?: string;
    report?: UserReport;
};

export type ClientEventsRequest = {
    events: Array<ClientEvent>;
};

export type ClientEventsResponse = {
    /**
     * The server-side switch for automatic collection.
     */
    collect?: 'on' | 'off';
    /**
     * Shown to the user after a manual problem report.
     */
    reportId?: string;
};

export type User = {
    id: string;
    email: string;
    name?: string;
    createdAt: string;
};

export type SessionResponse = {
    user: User | null;
    csrfToken: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
    locale: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    token: string;
    password: string;
};

export type CheckoutRequest = {
    plan: string;
};

export type RedirectUrl = {
    url: string;
};

export type HealthResponse = {
    status: 'ok';
    release?: string;
};

export type JobId = string;

export type DocId = string;

export type ModuleIdPath = ModuleId;

export const Provider = {
    GOOGLE: 'google',
    GITHUB: 'github',
    ORCID: 'orcid'
} as const;

export type Provider = typeof Provider[keyof typeof Provider];

export type JobToken = string;

/**
 * One key per user intent to start a check. The client mints a new one when the content
 * of the submission changes and when the previous job reaches a terminal state
 * (section 4.2).
 *
 */
export type IdempotencyKey = string;

/**
 * `gzip` when the client compressed the body, which it does itself since `fetch` does
 * not. Both values are accepted at any body size (section 2.6).
 *
 */
export const ContentEncoding = { GZIP: 'gzip', IDENTITY: 'identity' } as const;

/**
 * `gzip` when the client compressed the body, which it does itself since `fetch` does
 * not. Both values are accepted at any body size (section 2.6).
 *
 */
export type ContentEncoding = typeof ContentEncoding[keyof typeof ContentEncoding];

/**
 * When supplied, the server reuses this value in the response and its logs.
 */
export type RequestId = string;

export type SubmitJobData = {
    body: SubmitJobRequest;
    headers: {
        /**
         * One key per user intent to start a check. The client mints a new one when the content
         * of the submission changes and when the previous job reaches a terminal state
         * (section 4.2).
         *
         */
        'Idempotency-Key': string;
        /**
         * `gzip` when the client compressed the body, which it does itself since `fetch` does
         * not. Both values are accepted at any body size (section 2.6).
         *
         */
        'Content-Encoding'?: 'gzip' | 'identity';
        /**
         * When supplied, the server reuses this value in the response and its logs.
         */
        'X-Request-Id'?: string;
    };
    path?: never;
    query?: never;
    url: '/jobs';
};

export type SubmitJobErrors = {
    /**
     * The body failed validation, or a reference in it names something absent.
     */
    400: ApiError;
    /**
     * The request needs a signed-in principal.
     */
    401: ApiError;
    /**
     * A paid module was requested and access is not open.
     */
    402: ApiError;
    /**
     * Missing or mismatched CSRF token.
     */
    403: ApiError;
    /**
     * An intake limit was exceeded; `params` names the limit (section 12).
     */
    413: ApiError;
    /**
     * An encoding other than gzip or identity.
     */
    415: ApiError;
    /**
     * The same idempotency key arrived with a different body.
     */
    422: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * The service is briefly unavailable.
     */
    503: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type SubmitJobError = SubmitJobErrors[keyof SubmitJobErrors];

export type SubmitJobResponses = {
    /**
     * The same idempotency key with the same body: the job that key already names,
     * whatever state it is in (section 4.2).
     *
     */
    200: SubmitJobResponse;
    /**
     * The job was created.
     */
    202: SubmitJobResponse;
};

export type SubmitJobResponse2 = SubmitJobResponses[keyof SubmitJobResponses];

export type CancelJobData = {
    body?: never;
    headers: {
        'X-Job-Token': string;
        /**
         * When supplied, the server reuses this value in the response and its logs.
         */
        'X-Request-Id'?: string;
    };
    path: {
        jobId: string;
    };
    query?: never;
    url: '/jobs/{jobId}';
};

export type CancelJobErrors = {
    /**
     * An unknown job, an erased job, or a valid job with a wrong token; the client treats the
     * three identically.
     *
     */
    404: ApiError;
    /**
     * The resource is not in a state that allows this operation.
     */
    409: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type CancelJobError = CancelJobErrors[keyof CancelJobErrors];

export type CancelJobResponses = {
    /**
     * The job is cancelled.
     */
    202: JobStatus;
};

export type CancelJobResponse = CancelJobResponses[keyof CancelJobResponses];

export type GetJobData = {
    body?: never;
    headers: {
        'X-Job-Token': string;
        /**
         * When supplied, the server reuses this value in the response and its logs.
         */
        'X-Request-Id'?: string;
    };
    path: {
        jobId: string;
    };
    query?: never;
    url: '/jobs/{jobId}';
};

export type GetJobErrors = {
    /**
     * An unknown job, an erased job, or a valid job with a wrong token; the client treats the
     * three identically.
     *
     */
    404: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * The state of the job.
     */
    200: JobStatus;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type GetModuleResultData = {
    body?: never;
    headers: {
        'X-Job-Token': string;
        /**
         * When supplied, the server reuses this value in the response and its logs.
         */
        'X-Request-Id'?: string;
    };
    path: {
        jobId: string;
        docId: string;
        moduleId: ModuleId;
    };
    query?: never;
    url: '/jobs/{jobId}/documents/{docId}/modules/{moduleId}/result';
};

export type GetModuleResultErrors = {
    /**
     * An unknown job, an erased job, or a valid job with a wrong token; the client treats the
     * three identically.
     *
     */
    404: ApiError;
    /**
     * The resource is not in a state that allows this operation.
     */
    409: ApiError;
    /**
     * The result of an attempt that a retry has replaced.
     */
    410: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type GetModuleResultError = GetModuleResultErrors[keyof GetModuleResultErrors];

export type GetModuleResultResponses = {
    /**
     * The findings this module made about this document.
     */
    200: ModuleResult;
};

export type GetModuleResultResponse = GetModuleResultResponses[keyof GetModuleResultResponses];

export type RetryModuleData = {
    body?: RetryRequest;
    headers: {
        'X-Job-Token': string;
        /**
         * When supplied, the server reuses this value in the response and its logs.
         */
        'X-Request-Id'?: string;
    };
    path: {
        jobId: string;
        moduleId: ModuleId;
    };
    query?: never;
    url: '/jobs/{jobId}/modules/{moduleId}/retry';
};

export type RetryModuleErrors = {
    /**
     * An unknown job, an erased job, or a valid job with a wrong token; the client treats the
     * three identically.
     *
     */
    404: ApiError;
    /**
     * The resource is not in a state that allows this operation.
     */
    409: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type RetryModuleError = RetryModuleErrors[keyof RetryModuleErrors];

export type RetryModuleResponses = {
    /**
     * The retry was accepted; the refreshed job state.
     */
    202: JobStatus;
};

export type RetryModuleResponse = RetryModuleResponses[keyof RetryModuleResponses];

export type StreamJobEventsData = {
    body?: never;
    headers: {
        'X-Job-Token': string;
    };
    path: {
        jobId: string;
    };
    query?: never;
    url: '/jobs/{jobId}/events';
};

export type StreamJobEventsErrors = {
    /**
     * An unknown job, an erased job, or a valid job with a wrong token; the client treats the
     * three identically.
     *
     */
    404: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type StreamJobEventsError = StreamJobEventsErrors[keyof StreamJobEventsErrors];

export type StreamJobEventsResponses = {
    /**
     * A sequence of `event: status` frames whose data is a JobStatus, followed by
     * one `event: done` frame.
     *
     */
    200: string;
};

export type StreamJobEventsResponse = StreamJobEventsResponses[keyof StreamJobEventsResponses];

export type GetEntitlementsData = {
    body?: never;
    headers?: {
        /**
         * When supplied, the server reuses this value in the response and its logs.
         */
        'X-Request-Id'?: string;
    };
    path?: never;
    query?: never;
    url: '/entitlements';
};

export type GetEntitlementsErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type GetEntitlementsError = GetEntitlementsErrors[keyof GetEntitlementsErrors];

export type GetEntitlementsResponses = {
    /**
     * The state of access for the current principal.
     */
    200: Entitlements;
};

export type GetEntitlementsResponse = GetEntitlementsResponses[keyof GetEntitlementsResponses];

export type ScoutSearchData = {
    body: ScoutRequest;
    headers?: {
        /**
         * When supplied, the server reuses this value in the response and its logs.
         */
        'X-Request-Id'?: string;
    };
    path?: never;
    query?: never;
    url: '/scout/search';
};

export type ScoutSearchErrors = {
    /**
     * The body failed validation, or a reference in it names something absent.
     */
    400: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * The service is briefly unavailable.
     */
    503: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type ScoutSearchError = ScoutSearchErrors[keyof ScoutSearchErrors];

export type ScoutSearchResponses = {
    /**
     * The records the databases returned.
     */
    200: ScoutResponse;
};

export type ScoutSearchResponse = ScoutSearchResponses[keyof ScoutSearchResponses];

export type ScoutFeedbackData = {
    body: ScoutFeedbackRequest;
    path?: never;
    query?: never;
    url: '/scout/feedback';
};

export type ScoutFeedbackErrors = {
    /**
     * The body failed validation, or a reference in it names something absent.
     */
    400: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type ScoutFeedbackError = ScoutFeedbackErrors[keyof ScoutFeedbackErrors];

export type ScoutFeedbackResponses = {
    /**
     * Recorded.
     */
    204: void;
};

export type ScoutFeedbackResponse = ScoutFeedbackResponses[keyof ScoutFeedbackResponses];

export type ListVenuesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/venues';
};

export type ListVenuesErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type ListVenuesError = ListVenuesErrors[keyof ListVenuesErrors];

export type ListVenuesResponses = {
    /**
     * The preset list.
     */
    200: VenuesResponse;
};

export type ListVenuesResponse = ListVenuesResponses[keyof ListVenuesResponses];

export type FetchVenueRequirementsData = {
    body: VenueFetchRequest;
    headers?: {
        /**
         * When supplied, the server reuses this value in the response and its logs.
         */
        'X-Request-Id'?: string;
    };
    path?: never;
    query?: never;
    url: '/venues/fetch';
};

export type FetchVenueRequirementsErrors = {
    /**
     * The body failed validation, or a reference in it names something absent.
     */
    400: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * The address could not be read.
     */
    502: ApiError;
    /**
     * The address did not answer in time.
     */
    504: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type FetchVenueRequirementsError = FetchVenueRequirementsErrors[keyof FetchVenueRequirementsErrors];

export type FetchVenueRequirementsResponses = {
    /**
     * The page was read.
     */
    200: VenueFetchResponse;
};

export type FetchVenueRequirementsResponse = FetchVenueRequirementsResponses[keyof FetchVenueRequirementsResponses];

export type SendClientEventsData = {
    body: ClientEventsRequest;
    path?: never;
    query?: never;
    url: '/client-events';
};

export type SendClientEventsErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type SendClientEventsError = SendClientEventsErrors[keyof SendClientEventsErrors];

export type SendClientEventsResponses = {
    /**
     * The batch was received.
     */
    202: ClientEventsResponse;
};

export type SendClientEventsResponse = SendClientEventsResponses[keyof SendClientEventsResponses];

export type ReportCspViolationData = {
    /**
     * The `report-to` payload, as the browser sends it.
     */
    body: Array<{
        [key: string]: unknown;
    }>;
    path?: never;
    query?: never;
    url: '/csp-report';
};

export type ReportCspViolationErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type ReportCspViolationError = ReportCspViolationErrors[keyof ReportCspViolationErrors];

export type ReportCspViolationResponses = {
    /**
     * Received.
     */
    204: void;
};

export type ReportCspViolationResponse = ReportCspViolationResponses[keyof ReportCspViolationResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetSessionErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * The principal and the CSRF token.
     */
    200: SessionResponse;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * The body failed validation, or a reference in it names something absent.
     */
    400: ApiError;
    /**
     * The resource is not in a state that allows this operation.
     */
    409: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * The account was created and the session cookie set.
     */
    204: void;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * The request needs a signed-in principal.
     */
    401: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Signed in; the session cookie is set.
     */
    204: void;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Signed out; the cookie is cleared.
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/password/forgot';
};

export type ForgotPasswordErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type ForgotPasswordError = ForgotPasswordErrors[keyof ForgotPasswordErrors];

export type ForgotPasswordResponses = {
    /**
     * Accepted.
     */
    204: void;
};

export type ForgotPasswordResponse = ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/password/reset';
};

export type ResetPasswordErrors = {
    /**
     * The body failed validation, or a reference in it names something absent.
     */
    400: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * The password was set.
     */
    204: void;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type StartOauthData = {
    body?: never;
    path: {
        provider: 'google' | 'github' | 'orcid';
    };
    query?: {
        /**
         * A relative path within the application to return to.
         */
        next?: string;
    };
    url: '/auth/oauth/{provider}/start';
};

export type StartOauthErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type StartOauthError = StartOauthErrors[keyof StartOauthErrors];

export type StartOauthResponses = {
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type StartOauthResponse = StartOauthResponses[keyof StartOauthResponses];

export type CompleteOauthData = {
    body?: never;
    path: {
        provider: 'google' | 'github' | 'orcid';
    };
    query: {
        code: string;
        state: string;
    };
    url: '/auth/oauth/{provider}/callback';
};

export type CompleteOauthErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type CompleteOauthError = CompleteOauthErrors[keyof CompleteOauthErrors];

export type CompleteOauthResponses = {
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type CompleteOauthResponse = CompleteOauthResponses[keyof CompleteOauthResponses];

export type ExportAccountDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/export';
};

export type ExportAccountDataErrors = {
    /**
     * The request needs a signed-in principal.
     */
    401: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type ExportAccountDataError = ExportAccountDataErrors[keyof ExportAccountDataErrors];

export type ExportAccountDataResponses = {
    /**
     * The account's own records, as JSON.
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExportAccountDataResponse = ExportAccountDataResponses[keyof ExportAccountDataResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/delete';
};

export type DeleteAccountErrors = {
    /**
     * The request needs a signed-in principal.
     */
    401: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Accepted.
     */
    204: void;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type StartCheckoutData = {
    body: CheckoutRequest;
    path?: never;
    query?: never;
    url: '/billing/checkout';
};

export type StartCheckoutErrors = {
    /**
     * The request needs a signed-in principal.
     */
    401: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type StartCheckoutError = StartCheckoutErrors[keyof StartCheckoutErrors];

export type StartCheckoutResponses = {
    /**
     * The address to redirect the browser to.
     */
    200: RedirectUrl;
};

export type StartCheckoutResponse = StartCheckoutResponses[keyof StartCheckoutResponses];

export type OpenBillingPortalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/portal';
};

export type OpenBillingPortalErrors = {
    /**
     * The request needs a signed-in principal.
     */
    401: ApiError;
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type OpenBillingPortalError = OpenBillingPortalErrors[keyof OpenBillingPortalErrors];

export type OpenBillingPortalResponses = {
    /**
     * The address to redirect the browser to.
     */
    200: RedirectUrl;
};

export type OpenBillingPortalResponse = OpenBillingPortalResponses[keyof OpenBillingPortalResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthErrors = {
    /**
     * A request was refused for volume (section 2.9).
     */
    429: ApiError;
    /**
     * Any other failure. Every non-2xx response carries the same envelope, so a client has one
     * branch for a status it was not built to expect (section 2.8).
     *
     */
    default: ApiError;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * The service is up.
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];
