// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zModuleId = z.enum([
    'bibcheck',
    'glossary',
    'presubmit',
    'cite'
]);

export const zDocRole = z.enum([
    'manuscript',
    'bibliography',
    'glossary',
    'venue-requirements',
    'unknown'
]);

export const zSourceFormat = z.enum([
    'pdf',
    'docx',
    'md',
    'tex',
    'bib',
    'gls',
    'txt',
    'typed'
]);

export const zSeverity = z.enum([
    'critical',
    'warning',
    'info'
]);

export const zJobState = z.enum([
    'queued',
    'running',
    'partial',
    'finished',
    'failed',
    'cancelled'
]);

export const zModuleState = z.enum([
    'queued',
    'running',
    'ok',
    'error',
    'skipped'
]);

export const zStageState = z.enum([
    'pending',
    'running',
    'done',
    'error',
    'skipped'
]);

export const zLockReason = z.enum([
    'requires-account',
    'requires-paid',
    'trial-used',
    'period-ended'
]);

/**
 * A bibliographic database. The client names each one from its dictionary.
 */
export const zSourceId = z.enum([
    'crossref',
    'openalex',
    'semanticscholar',
    'pubmed',
    'arxiv',
    'doaj',
    'core',
    'datacite',
    'unpaywall',
    'europepmc'
]);

/**
 * Offsets are Unicode code points, which is the unit Python counts in natively and the
 * unit every measurement of text in this contract uses.
 *
 */
export const zOffsetUnit = z.literal('codepoints');

/**
 * Substitutions the client places into the wording it holds for a key.
 */
export const zParams = z.record(z.string(), z.union([
    z.string(),
    z.number()
]));

/**
 * A key into the client's dictionary, such as `bibcheck.retracted_entry`.
 */
export const zDictionaryKey = z.string().regex(/^[a-z][a-z0-9_]*(\.[a-z0-9_]+)+$/);

export const zSha256Hex = z.string().regex(/^[0-9a-f]{64}$/);

/**
 * An offset in Unicode code points.
 */
export const zCpOffset = z.int().gte(0);

export const zCounts = z.object({
    critical: z.int().gte(0),
    warning: z.int().gte(0),
    info: z.int().gte(0)
});

export const zApiError = z.object({
    error: z.object({
        code: z.string().regex(/^[A-Z][A-Z0-9_]*$/),
        requestId: z.string(),
        params: zParams.optional(),
        field: z.string().optional(),
        retryAfterSec: z.int().gte(0).optional(),
        message: z.string().optional()
    })
});

/**
 * The document information the parser read out of the file, which PreSubmit reads for
 * anonymity. The six standard keys are named; XMP entries and custom document properties
 * travel alongside them and are where a name most often survives.
 *
 */
export const zDocMeta = z.object({
    Author: z.string().optional(),
    Title: z.string().optional(),
    Subject: z.string().optional(),
    Creator: z.string().optional(),
    Producer: z.string().optional(),
    Keywords: z.string().optional()
});

/**
 * The venue this document targets. There are three ways to bring the requirements in - a
 * file, pasted text, or an address the server fetches for the client - and all three end
 * in the same place: the requirements are a document of this job, named here through
 * `docId`. `kind` records which way was used and `source` what the person
 * entered, both for the report rather than for the checking.
 *
 */
export const zVenueRef = z.object({
    kind: z.enum([
        'url',
        'text',
        'file'
    ]),
    source: z.string(),
    docId: z.uuid()
});

/**
 * A settings snapshot for all four modules, sent in full with every document so that a
 * re-run inside the same job is unambiguous.
 *
 */
export const zCheckOptions = z.object({
    bibcheck: z.object({
        verifyLive: z.boolean(),
        showOrphans: z.boolean(),
        unifyKeys: z.boolean(),
        keyFormat: z.enum([
            'author-year',
            'author-year-title',
            'author-title-year',
            'numeric'
        ]),
        sortBy: z.enum([
            'author',
            'year',
            'title',
            'key',
            'cited-order',
            'original'
        ]),
        countCommented: z.boolean()
    }),
    glossary: z.object({
        domain: z.string().optional()
    }),
    presubmit: z.object({
        anonymity: z.boolean()
    }),
    cite: z.object({
        source: z.enum(['document', 'excerpt']),
        excerpt: z.string().optional(),
        maxPerClaim: z.int().gte(1),
        instructions: z.string().optional()
    })
});

export const zSubmitDocument = z.object({
    docId: z.uuid(),
    name: z.string(),
    role: zDocRole,
    format: zSourceFormat,
    checks: z.array(zModuleId),
    uses: z.array(z.uuid()).optional(),
    options: zCheckOptions,
    text: z.string(),
    textSha256: zSha256Hex,
    cpLength: zCpOffset,
    meta: zDocMeta.optional(),
    venue: zVenueRef.optional()
});

export const zSubmitJobRequest = z.object({
    documents: z.array(zSubmitDocument).min(1),
    locale: z.string()
});

export const zRetryRequest = z.object({
    docIds: z.array(z.uuid()).optional()
});

export const zStage = z.object({
    id: z.string(),
    labelKey: zDictionaryKey,
    labelParams: zParams.optional(),
    docId: z.uuid().optional(),
    state: zStageState,
    startedAt: z.iso.datetime().optional(),
    finishedAt: z.iso.datetime().optional(),
    progress: z.object({
        done: z.int().gte(0),
        total: z.int().gte(0)
    }).optional(),
    detailKey: zDictionaryKey.optional(),
    detailParams: zParams.optional()
});

export const zModuleStatus = z.object({
    state: zModuleState,
    attempt: z.int().gte(1),
    score: z.int().gte(0).lte(100).nullable(),
    counts: zCounts,
    headlineKey: zDictionaryKey.optional(),
    headlineParams: zParams.optional(),
    errorCode: z.string().optional(),
    skippedReasonKey: zDictionaryKey.optional(),
    skippedReasonParams: zParams.optional(),
    resultRef: z.string().optional(),
    finishedAt: z.iso.datetime().optional()
});

export const zJobDocument = z.object({
    docId: z.uuid(),
    name: z.string(),
    role: zDocRole,
    textSha256: zSha256Hex,
    cpLength: zCpOffset,
    modules: z.object({
        bibcheck: zModuleStatus.optional(),
        glossary: zModuleStatus.optional(),
        presubmit: zModuleStatus.optional(),
        cite: zModuleStatus.optional()
    })
});

export const zJobStatus = z.object({
    id: z.uuid(),
    createdAt: z.iso.datetime(),
    state: zJobState,
    pollAfterMs: z.int().gte(0).optional(),
    stages: z.array(zStage),
    documents: z.array(zJobDocument)
});

export const zTextRef = z.object({
    docId: z.uuid(),
    textSha256: zSha256Hex,
    cpLength: zCpOffset
});

export const zArtifact = z.object({
    kind: z.enum([
        'bib',
        'tex',
        'md',
        'txt'
    ]),
    labelKey: zDictionaryKey,
    content: z.string()
});

/**
 * The document the place is in, when it is a different document from the one this result
 * is about. Every id used this way appears in `texts[]`.
 *
 */
export const zAnchorDocId = z.uuid();

/**
 * An anchor whose kind this schema version does not define.
 */
export const zAnchorUnknown = z.object({
    kind: z.string(),
    docId: zAnchorDocId.optional()
});

/**
 * Verbatim neighbouring text, present on every anchor of kind range, quote or point - 64
 * code points a side is ample. `prefix` ends exactly at the left boundary of the place and
 * `suffix` begins exactly at its right boundary. Optional here so that a missing context
 * costs its own anchor rather than the whole result, though the server always sends it.
 *
 */
export const zAnchorContext = z.string();

/**
 * The module knows the exact coordinates. `quote` is verbatim equal to the submitted text
 * between the offsets, and its length in code points equals `to - from`. Context is
 * present, as on every anchor that has one.
 *
 */
export const zAnchorRange = z.object({
    kind: z.literal('range'),
    docId: zAnchorDocId.optional(),
    from: zCpOffset,
    to: zCpOffset,
    quote: z.string(),
    prefix: zAnchorContext.optional(),
    suffix: zAnchorContext.optional()
});

/**
 * The module knows the text of the place, which is the right answer for a module working
 * on its own representation of the document. Context is present, and here at least one of
 * `prefix`/`suffix` is non-empty, since there are no coordinates to fall back on.
 *
 */
export const zAnchorQuote = z.object({
    kind: z.literal('quote'),
    docId: zAnchorDocId.optional(),
    quote: z.string(),
    prefix: zAnchorContext.optional(),
    suffix: zAnchorContext.optional(),
    near: zCpOffset.optional()
});

/**
 * An insertion position rather than a span. At least one of `prefix`/`suffix` is non-empty
 * and verbatim, which is what lets the point be verified and re-found after an edit.
 *
 */
export const zAnchorPoint = z.object({
    kind: z.literal('point'),
    docId: zAnchorDocId.optional(),
    at: zCpOffset,
    prefix: zAnchorContext.optional(),
    suffix: zAnchorContext.optional()
});

/**
 * A bibliography entry, addressed by a key that exists in the client's bibliography map or
 * literally in the submitted text.
 *
 */
export const zAnchorBibkey = z.object({
    kind: z.literal('bibkey'),
    docId: zAnchorDocId.optional(),
    bibkey: z.string()
});

/**
 * The finding is about the document as a whole.
 */
export const zAnchorDocument = z.object({
    kind: z.literal('document'),
    docId: zAnchorDocId.optional()
});

/**
 * Tagged by `kind`. The last branch matches a kind this version of the schema does not
 * define, so an anchor of a new kind parses and the client shows the finding without a
 * jump target instead of losing the response.
 *
 */
export const zAnchor = z.union([
    zAnchorRange,
    zAnchorQuote,
    zAnchorPoint,
    zAnchorBibkey,
    zAnchorDocument,
    zAnchorUnknown
]);

/**
 * A fact whose kind this schema version does not define.
 */
export const zEvidenceUnknown = z.object({
    kind: z.string()
});

/**
 * Rendered with rel="noopener noreferrer".
 */
export const zHttpUrl = z.url().regex(/^https?:\/\//);

export const zEvidenceDoi = z.object({
    kind: z.literal('doi'),
    value: z.string()
});

export const zEvidenceUrl = z.object({
    kind: z.literal('url'),
    value: zHttpUrl
});

export const zEvidenceDate = z.object({
    kind: z.literal('date'),
    labelKey: zDictionaryKey,
    value: z.iso.date()
});

export const zEvidenceNumber = z.object({
    kind: z.literal('number'),
    labelKey: zDictionaryKey,
    value: z.number()
});

export const zEvidenceText = z.object({
    kind: z.literal('text'),
    labelKey: zDictionaryKey,
    value: z.string()
});

export const zEvidenceSource = z.object({
    kind: z.literal('source'),
    labelKey: zDictionaryKey,
    title: z.string(),
    url: zHttpUrl.optional()
});

/**
 * Tagged by `kind`. A fact of a kind this schema version does not define parses and the
 * card passes over it, showing the rest.
 *
 */
export const zEvidence = z.union([
    zEvidenceDoi,
    zEvidenceUrl,
    zEvidenceDate,
    zEvidenceNumber,
    zEvidenceText,
    zEvidenceSource,
    zEvidenceUnknown
]);

/**
 * An action whose kind this schema version does not define.
 */
export const zActionUnknown = z.object({
    kind: z.string()
});

export const zActionCopy = z.object({
    kind: z.literal('copy'),
    labelKey: zDictionaryKey.optional(),
    value: z.string()
});

/**
 * The ready replacement text the Apply button inserts. `anchorIndex` names the anchor it
 * applies to, and that anchor is of kind `range`.
 *
 */
export const zActionReplace = z.object({
    kind: z.literal('replace'),
    labelKey: zDictionaryKey.optional(),
    value: z.string(),
    anchorIndex: z.int().gte(0).optional().default(0)
});

export const zActionOpenSource = z.object({
    kind: z.literal('openSource'),
    labelKey: zDictionaryKey.optional(),
    url: zHttpUrl
});

export const zActionDownload = z.object({
    kind: z.literal('download'),
    labelKey: zDictionaryKey.optional(),
    artifact: z.int().gte(0)
});

/**
 * Tagged by `kind`. An action of a kind this schema version does not define parses and the
 * card does not offer that button, offering the rest.
 *
 */
export const zIssueAction = z.union([
    zActionCopy,
    zActionReplace,
    zActionOpenSource,
    zActionDownload,
    zActionUnknown
]);

/**
 * A work as the databases returned it. Every field is third-party data and reaches the DOM
 * as a text node.
 *
 */
export const zBiblioRecord = z.object({
    title: z.string(),
    authors: z.array(z.string()),
    year: z.int().optional(),
    venue: z.string().optional(),
    citedBy: z.int().gte(0).optional(),
    doi: z.string().optional(),
    url: zHttpUrl.optional(),
    openAccess: z.boolean(),
    sources: z.array(zSourceId).min(1),
    abstract: z.string().optional()
});

export const zCiteCandidate = zBiblioRecord.and(z.object({
    candidateId: z.string(),
    relevance: z.number().gte(0).lte(1),
    alreadyCited: z.boolean(),
    lowRelevance: z.boolean()
}));

export const zCiteBlock = z.object({
    query: z.string(),
    candidates: z.array(zCiteCandidate)
});

export const zIssue = z.object({
    issueId: z.string(),
    code: z.string().regex(/^[A-Z][A-Z0-9_]*$/),
    severity: zSeverity,
    titleKey: zDictionaryKey,
    params: zParams.optional(),
    detail: z.string().optional(),
    anchors: z.array(zAnchor).min(1),
    evidence: z.array(zEvidence).optional(),
    actions: z.array(zIssueAction).optional(),
    cite: zCiteBlock.optional()
});

export const zModuleResult = z.object({
    module: zModuleId,
    docId: z.uuid(),
    attempt: z.int().gte(1),
    offsetUnit: zOffsetUnit,
    texts: z.array(zTextRef).min(1),
    issues: z.array(zIssue),
    artifacts: z.array(zArtifact).optional()
});

export const zModuleEntitlement = z.object({
    allowed: z.boolean(),
    lockReason: zLockReason.optional()
});

/**
 * Two independent answers. `modules[m].allowed` is the only source for the lock on module
 * m; `access` is the only source for what the launch row says about the period. Neither is
 * derived from the other: a trial run carries `allowed: true` with `access: false`.
 *
 */
export const zEntitlements = z.object({
    role: z.enum([
        'anonymous',
        'free',
        'paid'
    ]),
    access: z.boolean(),
    periodEndsAt: z.iso.datetime().optional(),
    modules: z.object({
        bibcheck: zModuleEntitlement,
        glossary: zModuleEntitlement,
        presubmit: zModuleEntitlement,
        cite: zModuleEntitlement
    })
});

export const zSubmitJobResponse = z.object({
    jobId: z.uuid(),
    jobToken: z.string(),
    createdAt: z.iso.datetime(),
    entitlements: zEntitlements
});

export const zScoutRequest = z.object({
    query: z.string().min(1),
    limit: z.union([
        z.literal(10),
        z.literal(25),
        z.literal(50),
        z.literal(100)
    ]),
    locale: z.string().optional()
});

export const zScoutResult = zBiblioRecord.and(z.object({
    resultId: z.string(),
    relevance: z.number().gte(0).lte(1).optional()
}));

export const zScoutResponse = z.object({
    results: z.array(zScoutResult),
    searchedSources: z.array(zSourceId),
    degraded: z.array(zSourceId).optional()
});

export const zScoutFeedbackRequest = z.object({
    resultId: z.string(),
    vote: z.enum(['up', 'down'])
});

export const zVenueFetchRequest = z.object({
    url: zHttpUrl
});

export const zVenueFetchResponse = z.object({
    state: z.enum(['ready', 'not-requirements']),
    text: z.string().optional(),
    title: z.string().optional(),
    fetchedAt: z.iso.datetime()
});

export const zBreadcrumb = z.object({
    action: z.string(),
    outcome: z.string(),
    ts: z.iso.datetime()
});

/**
 * Present on an event of kind `user_report`. The client shows the complete contents of the
 * report before it is sent.
 *
 */
export const zUserReport = z.object({
    message: z.string(),
    excerpt: z.string().optional()
});

export const zClientEvent = z.object({
    id: z.string(),
    ts: z.iso.datetime(),
    kind: z.enum([
        'js_error',
        'promise_rejection',
        'react_error',
        'worker_error',
        'api_error',
        'schema_error',
        'network_error',
        'extract_failed',
        'extract_suspicious',
        'slow_operation',
        'stalled_action',
        'blocked_action',
        'repeated_click',
        'anchor_degraded',
        'anchor_rejected',
        'anchor_budget',
        'storage_pressure',
        'user_report'
    ]),
    code: z.string(),
    fingerprint: z.string(),
    count: z.int().gte(1),
    release: z.string(),
    route: z.string(),
    locale: z.string(),
    theme: z.enum(['light', 'dark']),
    viewport: z.object({
        w: z.int(),
        h: z.int()
    }),
    context: z.record(z.string(), z.union([
        z.number(),
        z.boolean(),
        z.string()
    ])),
    breadcrumbs: z.array(zBreadcrumb),
    requestId: z.string().optional(),
    report: zUserReport.optional()
});

export const zClientEventsRequest = z.object({
    events: z.array(zClientEvent).min(1)
});

export const zClientEventsResponse = z.object({
    collect: z.enum(['on', 'off']).optional(),
    reportId: z.string().optional()
});

export const zUser = z.object({
    id: z.string(),
    email: z.email(),
    name: z.string().optional(),
    createdAt: z.iso.datetime()
});

export const zSessionResponse = z.object({
    user: zUser.nullable(),
    csrfToken: z.string()
});

export const zRegisterRequest = z.object({
    email: z.email(),
    password: z.string(),
    locale: z.string()
});

export const zLoginRequest = z.object({
    email: z.email(),
    password: z.string()
});

export const zForgotPasswordRequest = z.object({
    email: z.email()
});

export const zResetPasswordRequest = z.object({
    token: z.string(),
    password: z.string()
});

export const zCheckoutRequest = z.object({
    plan: z.string()
});

export const zRedirectUrl = z.object({
    url: z.url()
});

export const zHealthResponse = z.object({
    status: z.literal('ok'),
    release: z.string().optional()
});

export const zJobId = z.uuid();

export const zDocId = z.uuid();

export const zModuleIdPath = zModuleId;

export const zProvider = z.enum([
    'google',
    'github',
    'orcid'
]);

export const zJobToken = z.string();

/**
 * One key per user intent to start a check. The client mints a new one when the content
 * of the submission changes and when the previous job reaches a terminal state.
 *
 */
export const zIdempotencyKey = z.uuid();

/**
 * `gzip` when the client compressed the body, which it does itself since `fetch` does
 * not. Both values are accepted at any body size.
 *
 */
export const zContentEncoding = z.enum(['gzip', 'identity']);

/**
 * When supplied, the server reuses this value in the response and its logs.
 */
export const zRequestId = z.string();

export const zSubmitJobBody = zSubmitJobRequest;

export const zSubmitJobHeaders = z.object({
    'Idempotency-Key': z.uuid(),
    'Content-Encoding': z.enum(['gzip', 'identity']).optional(),
    'X-Request-Id': z.string().optional()
});

/**
 * The same idempotency key with the same body: the job that key already names,
 * whatever state it is in.
 *
 */
export const zSubmitJobResponse2 = zSubmitJobResponse;

export const zCancelJobHeaders = z.object({
    'X-Job-Token': z.string(),
    'X-Request-Id': z.string().optional()
});

export const zCancelJobPath = z.object({
    jobId: z.uuid()
});

/**
 * The job is cancelled.
 */
export const zCancelJobResponse = zJobStatus;

export const zGetJobHeaders = z.object({
    'X-Job-Token': z.string(),
    'X-Request-Id': z.string().optional()
});

export const zGetJobPath = z.object({
    jobId: z.uuid()
});

/**
 * The state of the job.
 */
export const zGetJobResponse = zJobStatus;

export const zGetModuleResultHeaders = z.object({
    'X-Job-Token': z.string(),
    'X-Request-Id': z.string().optional()
});

export const zGetModuleResultPath = z.object({
    jobId: z.uuid(),
    docId: z.uuid(),
    moduleId: zModuleId
});

/**
 * The findings this module made about this document.
 */
export const zGetModuleResultResponse = zModuleResult;

export const zRetryModuleBody = zRetryRequest;

export const zRetryModuleHeaders = z.object({
    'X-Job-Token': z.string(),
    'X-Request-Id': z.string().optional()
});

export const zRetryModulePath = z.object({
    jobId: z.uuid(),
    moduleId: zModuleId
});

/**
 * The retry was accepted; the refreshed job state.
 */
export const zRetryModuleResponse = zJobStatus;

export const zStreamJobEventsHeaders = z.object({
    'X-Job-Token': z.string()
});

export const zStreamJobEventsPath = z.object({
    jobId: z.uuid()
});

/**
 * A sequence of `event: status` frames whose data is a JobStatus, followed by
 * one `event: done` frame.
 *
 */
export const zStreamJobEventsResponse = z.string();

export const zGetEntitlementsHeaders = z.object({
    'X-Request-Id': z.string().optional()
});

/**
 * The state of access for the current principal.
 */
export const zGetEntitlementsResponse = zEntitlements;

export const zScoutSearchBody = zScoutRequest;

export const zScoutSearchHeaders = z.object({
    'X-Request-Id': z.string().optional()
});

/**
 * The records the databases returned.
 */
export const zScoutSearchResponse = zScoutResponse;

export const zScoutFeedbackBody = zScoutFeedbackRequest;

/**
 * Recorded.
 */
export const zScoutFeedbackResponse = z.void();

export const zFetchVenueRequirementsBody = zVenueFetchRequest;

export const zFetchVenueRequirementsHeaders = z.object({
    'X-Request-Id': z.string().optional()
});

/**
 * The page was read.
 */
export const zFetchVenueRequirementsResponse = zVenueFetchResponse;

export const zSendClientEventsBody = zClientEventsRequest;

/**
 * The batch was received.
 */
export const zSendClientEventsResponse = zClientEventsResponse;

/**
 * The `report-to` payload, as the browser sends it.
 */
export const zReportCspViolationBody = z.array(z.record(z.string(), z.unknown()));

/**
 * Received.
 */
export const zReportCspViolationResponse = z.void();

/**
 * The principal and the CSRF token.
 */
export const zGetSessionResponse = zSessionResponse;

export const zRegisterBody = zRegisterRequest;

/**
 * The account was created and the session cookie set.
 */
export const zRegisterResponse = z.void();

export const zLoginBody = zLoginRequest;

/**
 * Signed in; the session cookie is set.
 */
export const zLoginResponse = z.void();

/**
 * Signed out; the cookie is cleared.
 */
export const zLogoutResponse = z.void();

export const zForgotPasswordBody = zForgotPasswordRequest;

/**
 * Accepted.
 */
export const zForgotPasswordResponse = z.void();

export const zResetPasswordBody = zResetPasswordRequest;

/**
 * The password was set.
 */
export const zResetPasswordResponse = z.void();

export const zStartOauthPath = z.object({
    provider: z.enum([
        'google',
        'github',
        'orcid'
    ])
});

export const zStartOauthQuery = z.object({
    next: z.string().regex(/^\/([^\/\\].*)?$/).optional().default('/')
});

/**
 * Any other failure. Every non-2xx response carries the same envelope, so a client has one
 * branch for a status it was not built to expect.
 *
 */
export const zStartOauthResponse = zApiError;

export const zCompleteOauthPath = z.object({
    provider: z.enum([
        'google',
        'github',
        'orcid'
    ])
});

export const zCompleteOauthQuery = z.object({
    code: z.string(),
    state: z.string()
});

/**
 * Any other failure. Every non-2xx response carries the same envelope, so a client has one
 * branch for a status it was not built to expect.
 *
 */
export const zCompleteOauthResponse = zApiError;

/**
 * The account's own records, as JSON.
 */
export const zExportAccountDataResponse = z.record(z.string(), z.unknown());

/**
 * Accepted.
 */
export const zDeleteAccountResponse = z.void();

export const zStartCheckoutBody = zCheckoutRequest;

/**
 * The address to redirect the browser to.
 */
export const zStartCheckoutResponse = zRedirectUrl;

/**
 * The address to redirect the browser to.
 */
export const zOpenBillingPortalResponse = zRedirectUrl;

/**
 * The service is up.
 */
export const zHealthResponse2 = zHealthResponse;
